# examples.py

from .graph import Graph
import numpy as np


def create_D2n(n):
    """
    

    Parameters
    ----------
    n : int
        non-negative integer.

    Returns
    -------
    D2n : Graph
        Dyhedral group of 2n elements with rotation a and reflection b.

    """
    D2n=Graph(["a","b"],np.array([[[] for _ in range(2*n)]for _ in range(2*n)]))
    for i in range(n-1):
        D2n.add_edge(i,i+1,label="a")
    D2n.add_edge(n-1, 0, "a")
    for i in range(n-1):
        D2n.add_edge(i+n+1,i+n,label="a")
    D2n.add_edge(n, 2*n-1, "a")

    for i in range(n):
        D2n.add_edge(i,i+n,label="b")
    return D2n


def create_Cn(n):
    """
    

    Parameters
    ----------
    n : int
        non-negative integer.

    Returns
    -------
    Cn : Graph
        Cyclic group of order n generated by c.

    """
    Cn=Graph(["c"],np.array([[[] for _ in range(n)]for _ in range(n)]))
    for i in range(n):
        Cn.add_edge(i,(i+1)%n,label="c")
    return Cn