# groups.py

from stallings_amalgams import Graph
import numpy as np
from stallings_amalgams.visualization import visualize,datatotex


def create_D2n(n: int,labels = ["a","b"]) -> Graph:
    """
    

    Parameters
    ----------
    n : int
        positive integer.

    Returns
    -------
    D2n : Graph
        Dihedral group of 2n elements with rotation a and reflection b.

    """
    a = labels[0]
    b = labels[1]
    if n < 1:
        raise ValueError("n must be a non-negative integer")
    
    D2n=Graph([a,b],np.array([[[] for _ in range(2*n)]for _ in range(2*n)]))
    for i in range(n-1):
        D2n.add_edge(i,i+1,label=a)
    D2n.add_edge(n-1, 0, a)
    for i in range(n-1):
        D2n.add_edge(i+n+1,i+n,label=a)
    D2n.add_edge(n, 2*n-1, a)

    for i in range(n):
        D2n.add_edge(i,i+n,label=b)
        D2n.add_edge(i+n,i,label=b)
    return D2n


def create_Cn(n: int, labels = ["c"]) -> Graph:
    """
    

    Parameters
    ----------
    n : int
        non-negative integer.

    Returns
    -------
    Cn : Graph
        Cyclic group of order n generated by c.

    """
    c = labels[0]
    Cn=Graph([c],np.array([[[] for _ in range(n)]for _ in range(n)]))
    for i in range(n):
        Cn.add_edge(i,(i+1)%n,label=c)
    return Cn

def direct_product(G1: Graph, G2: Graph) -> Graph:
    """
    Make sure labels of G1 and G2 are distinct!
    """
    n1 = G1.n_verts
    n2 = G2.n_verts

    labels = G1.labels | G2.labels

    G = Graph(
        labels,
        np.array([[[] for _ in range(n1*n2)]
                  for _ in range(n1*n2)])
    )

    for i in range(n1):
        for j in range(n2):

            v = i*n2 + j

            for label in G1.labels:
                nbrs = np.nonzero(G1.mat[label][i])[0]

                for k in nbrs:
                    w = k*n2 + j
                    G.add_edge(v, w, label)

            for label in G2.labels:
                nbrs = np.nonzero(G2.mat[label][j])[0]

                for k in nbrs:
                    w = i*n2 + k
                    G.add_edge(v, w, label)

    return G

def semidirect_product(G1: Graph, G2:Graph, action: dict[str, dict[str, list[str]]]) -> Graph:
    """
    Make sure labels of G1 and G2 are distinct!
    """
    n1 = G1.n_verts
    n2 = G2.n_verts
    G = Graph(G1.labels | G2.labels,np.array([[[] for _ in range(n1*n2)]
              for _ in range(n1*n2)]))
    for label in G1.labels:
        for i,j in np.argwhere(G1.mat[label]):
            G.add_edge(i*n2, j*n2,label)
    
    for label in G2.labels:
        for r in range(n1):
            for i,j in np.argwhere(G2.mat[label]):
                G.add_edge(r*n2 + i, r*n2 + j,label)
            
    for b in action:
        for a in action[b]:
            for i in range(n1):
                for j in range(n2):
                    Gtemp = Graph(G1.labels | G2.labels)
                    Gtemp.add_edge(-1,0,b)
                    Gtemp.add_edge(1,-1,a)
                    Gtemp.add_edge(2,-1,b)
                    for c,letter in enumerate(reversed(action[b][a][1:])):
                        Gtemp.add_edge(3+c, -1,letter+"^-1")
                    Gtemp.add_edge(0,Gtemp.n_verts -1,action[b][a][0])
                    G.Wedge(Gtemp, i*n2 + j, 0)

    G.fold()                
    return(G)
                    
                        
            
            
            
            
            