import numpy as np
from stallings_amalgams import Graph, product_graph
from stallings_amalgams.words import inverse_word,inverse_label,tree_word
from stallings_amalgams.presentation import Presentation
from stallings_amalgams.precover import get_red_precover

def is_subgroup_member(
    G1: Graph,
    G2: Graph,
    A: dict[int, int],
    subgroup_generators: list[list[str]],
    word: list[str],
) -> bool:
    """
    Determine whether a word represents an element of a subgroup.

    The ambient group is the amalgamated free product G1 *_A G2. The
    subgroup is generated by ``subgroup_generators``. Membership is
    decided by constructing the reduced precover of the subgroup and
    checking whether ``word`` labels a closed path at its basepoint.

    Parameters
    ----------
    G1 : Graph
        Cayley graph of the first finite factor.

    G2 : Graph
        Cayley graph of the second finite factor.

    A : dict[int, int]
        Identification of the amalgamated subgroup in the two factors.
        Each key represents an element of G1, and the corresponding value
        represents the identified element of G2.

    subgroup_generators : list[list[str]]
        Words generating the subgroup whose membership problem is being
        considered. Each word is represented as a list of edge labels.

    word : list[str]
        Word to test for membership, represented as a list of edge labels.

    Returns
    -------
    bool
        ``True`` if ``word`` represents an element of the subgroup
        generated by ``subgroup_generators``; otherwise ``False``.
    """
    reduced_precover = get_red_precover(
        G1,
        G2,
        A,
        subgroup_generators,
    )

    endpoint = reduced_precover.read_word(
        reduced_precover.basepoint,
        word,
    )

    return endpoint == reduced_precover.basepoint

def subgroup_index(
    G1: Graph,
    G2: Graph,
    A: dict[int, int],
    subgroup_generators: list[list[str]]
) -> int | None:
    """
    Return the index of the generated subgroup, or ``None`` if the index
    is infinite.

    The ambient group is the amalgamated free product G1 *_A G2, and the
    subgroup is generated by ``subgroup_generators``.

    The function constructs the reduced precover representing the subgroup.
    The subgroup has finite index precisely when this reduced precover is a
    complete coset graph: from every vertex, every label of the ambient
    generating set must be readable.

    Parameters
    ----------
    G1 : Graph
    Cayley graph of the first finite factor.

    G2 : Graph
    Cayley graph of the second finite factor.

    A : dict[int, int]
    Identification of the amalgamated subgroup in the two factors.
    Each key represents an element of G1, and the corresponding value
    represents the identified element of G2.

    subgroup_generators : list[list[str]]
    Words generating the subgroup. Each word is represented as a list
    of edge labels.

    Returns
    -------
    int or None
    The index of the generated subgroup if the index is finite;
    otherwise ``None``.

    """
    reduced_precover = get_red_precover(G1,G2,A,subgroup_generators)
    if all(
    reduced_precover.mat[label].any(axis=1).all()
    for label in reduced_precover.labels
    ): # I.e. graph is saturated/complete
        return reduced_precover.n_verts

    return None

def is_free(
    G1: Graph,
    G2: Graph,
    A: dict[int, int],
    subgroup_generators: list[list[str]],
) -> bool:
    """
    Determine whether a finitely generated subgroup of G1 *_A G2 is free.

    Parameters
    ----------
    G1 : Graph
    Cayley graph of the first finite factor.

    G2 : Graph
    Cayley graph of the second finite factor.

    A : dict[int, int]
    Identification of the amalgamated subgroup in the two factors.

    subgroup_generators : list[list[str]]
    Words generating the subgroup.

    Returns
    -------
    bool
    ``True`` if the generated subgroup is free; otherwise ``False``.
    """
    reduced_precover = get_red_precover(G1,G2,A,subgroup_generators)
    G1comps = reduced_precover.monochromatic_components(G1)
    G2comps = reduced_precover.monochromatic_components(G2)
    components = [
        (C, G1) for C in G1comps
    ] + [
        (C, G2) for C in G2comps
    ]
    return all(
        reduced_precover.stabilizer(next(iter(component)),factor)=={factor.basepoint}
        for component,factor in components
        )

def get_presentation(G1: Graph,
    G2: Graph,
    A: dict[int,int],
    H: list[list[str]]
) -> Presentation:
    PH = get_red_precover(G1,G2, A, H)
    R1 = G1.get_pi1_gen_set()
    R2 = G2.get_pi1_gen_set()
    parent1, parent_label1, outside_edges1 = G1.spanning_tree_data()
    parent2, parent_label2, outside_edges2 = G2.spanning_tree_data()
    R12 = [ tree_word(a,parent1,parent_label1) 
           + 
           inverse_word(tree_word(A[a],parent2,parent_label2))  
           for a in A
    ]
    R = R1+R2+R12
    parentH, parent_labelH, outside_edgesH = PH.spanning_tree_data()
    assert type(outside_edgesH)==list, "code only works if outside_edges is a deterministic list"

    XH = [f"x{i}" for i in range(len(outside_edgesH))]
    RH = set()
    for v in range(PH.n_verts):
        for r in R:
            rel = []
            vertex = v
            readable = True
            for label in r:
                terminal = PH.next_vertex(vertex, label)
                if terminal is None:
                    readable = False
                    break
                x = (vertex, terminal, label)
                i = next((k for k, (u1,u2,letter) in enumerate(outside_edgesH) 
                    if (u1,u2,letter) == x or (u2,u1,inverse_label(letter)) == x), None
                ) # note that outside_edges only contains edges with positive labels
                if i is not None:
                    if label.endswith("^-1"):
                        rel+= [f"x{i}^-1"]
                    
                    else:
                        rel+=[f"x{i}"]
                vertex = terminal
            if readable:
                assert vertex == v, ("PH not a prevcover!",v, r, vertex)
                RH |= {tuple(rel)}

    generator_words = {
        f"x{i}": tree_word(u, parentH, parent_labelH)
                + [label]
                + inverse_word(tree_word(v, parentH, parent_labelH))
        for i, (u, v, label) in enumerate(outside_edgesH)
    }
    RH = [list(rel) for rel in RH]
    return Presentation(XH,RH,generator_words)

def intersection(
    G1: Graph,
    G2: Graph,
    A: dict[int, int],
    H: list[list[str]],
    K: list[list[str]],
) -> list[list[str]]:
    """Generators for the intersection of the subgroups <H> and <K>."""
    PH = get_red_precover(G1,G2,A,H)
    PK = get_red_precover(G1,G2,A,K)
    prod = product_graph(PH,PK)

    return prod.get_pi1_gen_set()